#dataset_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape/CubeTexturesForGraphQuad_gan_FC_processed
#mesh_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape-model/CubeTexturesForGraphQuad
#mesh_resolution: 128
#dataset_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape/CubeTexturePlaneQuad32_FC_processed
#mesh_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape-model/CubeTexturePlaneQuad32
#mesh_resolution: 32
#dataset_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape/CubeTexturesForGraphQuad32_FC_processed
#mesh_path: /cluster/gimli/ysiddiqui/CADTextures/SingleShape-model/CubeTexturesForGraphQuad32
#mesh_resolution: 64

dataset_path: /cluster/gimli/ysiddiqui/CADTextures/Photoshape/shapenet-chairs-manifold-highres-part_processed
mesh_path: /cluster/gimli/ysiddiqui/CADTextures/Photoshape/shapenet-chairs-manifold-highres
pairmeta_path: /cluster/gimli/ysiddiqui/CADTextures/Photoshape-model/metadata/pairs.json
df_path: /cluster/gimli/ysiddiqui/CADTextures/Photoshape-model/shapenet-chairs-manifold
image_path: /cluster/gimli/ysiddiqui/CADTextures/Photoshape/exemplars
mask_path: /cluster/gimli/ysiddiqui/CADTextures/Photoshape/exemplars_mask
condition_path: /cluster/gimli/ysiddiqui/CADTextures/Photoshape/shapenet-chairs-manifold_autoencoder
stat_path: /cluster/gimli/ysiddiqui/CADTextures/Photoshape/shapenet-chairs-manifold-highres_stat.pt
mesh_resolution: 64

experiment: fast_dev
seed: null
save_epoch: 1
sanity_steps: 1
max_epoch: 2000
scheduler: null
val_check_percent: 1.0
val_check_interval: 1
resume: null

num_mapping_layers: 2
lr_g: 0.002
lr_d: 0.00235
lr_e: 0.0001
lazy_gradient_penalty_interval: 16
lazy_path_penalty_after: 0
lazy_path_penalty_interval: 4
latent_dim: 512
condition_dim: 512
lambda_gp: 1
lambda_plp: 2
lambda_patch: 1
ada_start_p: 0.  #to disable set to -1
ada_target: 0.6
ada_interval: 4
ada_fixed: False
g_channel_base: 16384
d_channel_base: 16384
features: normal
#normal
#position
#position+normal
#normal+laplacian
#normal+ff1+ff2
#normal+curvature
#normal+laplacian+ff1+ff2+curvature

random_bg: white
colorspace: rgb

image_size: 128
num_patch_per_view: 4
patch_size: 64
image_size_hres: 512
erode: True

num_faces: [24576, 6144, 1536, 384, 96, 24]
#image_size: 32
#num_faces: [1024, 256, 64, 16]
#image_size: 64
#num_faces: [1536, 384, 96, 24]
num_eval_images: 2048
num_vis_images: 1024
num_vis_meshes: 64
batch_size: 16
views_per_sample: 2
random_views: False
num_workers: 8
blur_mask: False

df_trunc: 0.3125
df_size: 0.0625
df_mean: 0.2839
df_std: 0.0686

shape_id: shape02344_rank02_pair183269
epoch_steps: 320

mbstd_on: 1

create_new_resume: False

wandb_main: False
suffix: ''

preload: True

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: .
